### PR TITLE
Port SERIAL changes to ORM 3.0 & DBAL 4.0

### PR DESCRIPTION
**Pull request by fwolfsjaeger**
Port the changes from #3 to use CockroachDB's SERIAL generator to ORM 3.0 & DBAL 4.0.

### CODE REVIEW

**Comment by fwolfsjaeger** [comment]
@sweoggy You should have write access to the branch of this PR.

**Comment by sweoggy** [comment]
> @sweoggy You should have write access to the branch of this PR.

Thanks! I will have a look as soon as possible

**Comment by fwolfsjaeger** [comment]
Unit tests all pass and it looks good to me, What do you think?

**Comment by sweoggy** [comment]
> Unit tests all pass and it looks good to me, What do you think?

unique_rowid() are still added to JoinColumns in migrations, so I need to solve that first

**Comment by sweoggy** [comment]
@fwolfsjaeger this should be ready now!

**Comment by fwolfsjaeger** [comment]
Looks okay on first glance, I'll check it in detail and run some tests on Tuesday.

Thank you very much for your contribution!

**Comment by fwolfsjaeger** [comment]
Sorry for the delay, took me a little longer to find the time.

I've changed the operation priority in `src/ORM/Listener/RemoveDefaultFromForeignKeysListener.php`, could you please check if that's what was intended?

**Comment by sweoggy** [comment]
That looks good and working for me locally!

**Review by sweoggy — APPROVED** [review]

**Pull request merged**
