### PR TITLE
Improve support of CockroachDB's SERIAL primary key when using Doctrine ORM

### PR DESCRIPTION
**Pull request by sweoggy**
As title, as using the default IdentityGenerator causes

`ERROR:  currval(): could not determine data type of placeholder $1`

that's because CockroachDB doesn't support returning ID of last inserted row https://www.cockroachlabs.com/docs/stable/sql-faqs#how-do-i-get-the-last-id-serial-value-inserted-into-a-table

This implements a custom SerialGenerator, with necessary changes to BasicEntityPersister and CockroachDBPlatform. Unfortunuately BasicEntityPersister is hard to extend, so the entire class is rewritten (mostly copy-paste). It may look daunting at first, but this class rarely receives changes upstream, so I deem it not hard to maintain.

I can port this class to DBAL 4.0 after (if) this is merged to DBAL 3.8.

I will also add a corresponding service registration for the two listeners to the bundle after merge.

### CODE REVIEW

**Comment by sweoggy** [comment]
Hi @fwolfsjaeger please take a look when you get a chance :blush: 

TL:DR; This PR adds the ability to use CockroachDB's auto increment feature, which performs vastly better than the SequenceGenerator strategy.

**Comment by fwolfsjaeger** [comment]
Many thanks. I'll check it tomorrow.

**Comment by fwolfsjaeger** [comment]
Sorry for the delay.

I've checked your changes and I'm fine with most of them. I'm just not that happy about the override of the BasicEntityPersister.

I know that Doctrine is very protective of their core functions and rarely allows any overrides there. But, I've found another approach to this problem: [composer script to patch the imports](https://github.com/mediamonks/symfony-mssql-bundle/blob/master/Composer/ScriptHandler.php). This script has to be added in `composer.json` to `post-install-cmd` and `post-update-cmd`. What do you think?

If you don't mind, I would merge your changes and amend your code a little, incl. adding the composer script.

**Comment by fwolfsjaeger** [comment]
I've merged your changes to the branch `feature/serial-pk-3.8` and made additional changes there:
- added the composer script to patch the FQCNs to BasicEntityPersister
- amended the code style & PHPDoc blocks
- fixed the warning of your Unit test

Please check if everything still works as expected in that branch. Once you confirm that everything still works for you, I'd approve & merge your PR and cherry-pick my last commit on top. Then I'd amend the explanation in README.md and create a new release version.

**Review by fwolfsjaeger — APPROVED** [review]

**Comment by sweoggy** [comment]
> Sorry for the delay.
> 
> I've checked your changes and I'm fine with most of them. I'm just not that happy about the override of the BasicEntityPersister.
> 
> I know that Doctrine is very protective of their core functions and rarely allows any overrides there. But, I've found another approach to this problem: [composer script to patch the imports](https://github.com/mediamonks/symfony-mssql-bundle/blob/master/Composer/ScriptHandler.php). This script has to be added in `composer.json` to `post-install-cmd` and `post-update-cmd`. What do you think?
> 
> If you don't mind, I would merge your changes and amend your code a little, incl. adding the composer script.

thanks, that's super neat, didn't know that was possible!

**Comment by sweoggy** [comment]
> I've merged your changes to the branch `feature/serial-pk-3.8` and made additional changes there:
> 
>     * added the composer script to patch the FQCNs to BasicEntityPersister
> 
>     * amended the code style & PHPDoc blocks
> 
>     * fixed the warning of your Unit test
> 
> 
> Please check if everything still works as expected in that branch. Once you confirm that everything still works for you, I'd approve & merge your PR and cherry-pick my last commit on top. Then I'd amend the explanation in README.md and create a new release version.

I checked out your branch just now. It creates migrations just the same, however default value is no longer set correctly:

image

Compared with my branch:

image

**Edit:** Which was because the default entity manager was used:

image

Which was caused by me not adding the overrideBasicEntityPersister script to my composer.json. I suggest updating the README.md replacing my composer.json autoload patching instructions with your superior composer script.

All in all it seems to work great, thank you!

**Comment by fwolfsjaeger** [comment]
Changes are merged and the version is updated to 0.8.4. Thank you very much for the contribution!

**Comment by fwolfsjaeger** [comment]
I've add a feature branch and PR to port these changes to DBAL 4.0: #4

**Pull request merged**
